server:
  port: 10082
  servlet:
    context-path: /${artifactId}

spring:
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000s
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 2
        max-concurrency: 5
      test13:
        queue:
          name: test13_queue
        exchange:
          name: test13_exchange
          type: topic
        key: test13.#