server:
  port: 10081
  servlet:
    context-path: /${artifactId}


dubbo:
  application:
    name: ${artifactId}
    logger: slf4j
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    check: false
