# 开发环境配置

spring:
  redis:
    host: localhost
    port: 6379
    database: 0

# Dubbo配置
dubbo:
  application:
    name: ${artifactId}
    logger: slf4j
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20883
  scan:
    base-packages: com.cn.boot.sample.redis.service